"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import { ArrowDownRight, ArrowUpRight, Clock3, ExternalLink, Info, LockKeyhole, UsersRound } from "lucide-react";
import { AdminPageNote, StatusBadge } from "@/components/admin";
import { clientApi } from "@/lib/client-api";

function useAdminData<T>(url:string){
  const [data,setData]=useState<T>(); const [error,setError]=useState(""); const [requestKey,setRequestKey]=useState(0);
  useEffect(()=>{clientApi<T>(url).then(setData).catch(reason=>setError(reason.message))},[url,requestKey]);
  return {data,error,retry:()=>{setError("");setData(undefined);setRequestKey(value=>value+1)}};
}
function LoadState({error,retry}:{error:string;retry:()=>void}){return <div className="empty-state"><div><h3>{error?"Data belum dapat dimuat.":"Memuat data…"}</h3>{error&&<><p>{error}</p><button className="secondary-button" onClick={retry}>Coba lagi</button></>}</div></div>}
function NoRows({label}:{label:string}){return <div className="empty-state"><div><h3>Belum ada {label}.</h3><p>Data akan muncul di sini setelah tersimpan di Google Sheets.</p></div></div>}
const statusLabel:Record<string,string>={completed:"Selesai",in_progress:"Berlangsung",not_started:"Belum mulai"};

type AdminUser={id:string;name:string;email:string;nama?:string;usia?:string;jenis_kelamin?:string;assessment_status:string;updated_at:string};
type DashboardData={totalUsers:number;completed:number;inProgress:number;notStarted:number;spreadsheetUrl:string;recent:AdminUser[]};
export function AdminDashboard(){
  const {data,error,retry}=useAdminData<DashboardData>("/api/admin/dashboard"); if(!data)return <LoadState error={error} retry={retry}/>;
  const total=Math.max(data.totalUsers,1); const completion=Math.round((data.completed/total)*100);
  return <div className="admin-overview"><section className="metric-strip">{[["Total pengguna",String(data.totalUsers),"Responden terdaftar",UsersRound],["Sudah mengisi",String(data.completed),`${completion}% dari pengguna`,ArrowUpRight],["Belum selesai",String(data.inProgress),"Assessment berlangsung",Clock3],["Belum mulai",String(data.notStarted),"Belum ada assessment",ArrowDownRight]].map(([label,value,note,Icon])=><article key={label as string}><span><Icon/></span><p><small>{label as string}</small><strong>{value as string}</strong><b>{note as string}</b></p></article>)}</section><section className="admin-chart"><header><div><h2>Sumber data penelitian</h2><p>Data tersimpan langsung di spreadsheet pemilik riset.</p></div></header><div className="sheet-callout"><p><strong>Google Sheets aktif</strong><span>Periksa, koreksi, atau unduh data dari sumber utama.</span></p><a className="secondary-button" href={data.spreadsheetUrl} target="_blank" rel="noreferrer">Buka Google Sheets <ExternalLink size={17}/></a></div></section><section className="status-breakdown"><header><h2>Status responden</h2><span>Total {data.totalUsers}</span></header><div className="donut"><div><strong>{completion}%</strong><span>Selesai</span></div></div><ul><li><i className="done"/>Selesai <b>{data.completed}</b></li><li><i className="ongoing"/>Berlangsung <b>{data.inProgress}</b></li><li><i className="idle"/>Belum mulai <b>{data.notStarted}</b></li></ul></section><section className="recent-table"><header><h2>Aktivitas terbaru</h2><Link href="/admin/pengguna">Lihat semua →</Link></header>{data.recent.map(user=><div key={user.id}><span>{user.name.split(" ").map(x=>x[0]).join("").slice(0,2)}</span><p><strong>{user.name}</strong><small>{user.id} · {user.updated_at?new Date(user.updated_at).toLocaleDateString("id-ID"):"Belum mulai"}</small></p><b>{statusLabel[user.assessment_status]}</b></div>)}</section></div>
}

export function AdminUsersTable(){
  const {data,error,retry}=useAdminData<AdminUser[]>("/api/admin/users"); const [query,setQuery]=useState("");const [status,setStatus]=useState("all");
  const filtered=useMemo(()=>data?.filter(user=>(status==="all"||user.assessment_status===status)&&`${user.id} ${user.name} ${user.nama||""} ${user.email}`.toLowerCase().includes(query.toLowerCase()))||[],[data,query,status]);
  if(!data)return <LoadState error={error} retry={retry}/>; if(!data.length)return <NoRows label="responden"/>;
  return <div className="table-card"><div className="filter-bar"><input aria-label="Cari responden" placeholder="Cari ID, nama, atau email…" value={query} onChange={event=>setQuery(event.target.value)}/><select aria-label="Filter status" value={status} onChange={event=>setStatus(event.target.value)}><option value="all">Semua status</option><option value="completed">Selesai</option><option value="in_progress">Berlangsung</option><option value="not_started">Belum mulai</option></select><span>{filtered.length} responden</span></div>{filtered.length?<div className="table-scroll"><table><thead><tr><th>ID</th><th>Nama</th><th>Email</th><th>Usia</th><th>Jenis kelamin</th><th>Status</th><th>Aktivitas terakhir</th></tr></thead><tbody>{filtered.map(user=><tr key={user.id}><td><Link href={`/admin/pengguna/${encodeURIComponent(user.id)}`}><strong>{user.id}</strong></Link></td><td>{user.nama||user.name}</td><td>{user.email}</td><td>{user.usia||"—"}</td><td>{user.jenis_kelamin||"—"}</td><td><StatusBadge status={statusLabel[user.assessment_status]}/></td><td>{user.updated_at?new Date(user.updated_at).toLocaleString("id-ID"):"—"}</td></tr>)}</tbody></table></div>:<NoRows label="hasil yang cocok"/>}</div>
}

type ResponseRow=Record<string,string|number> & {assessment_id:string;user_id:string;updated_at:string};
export function AdminResponses(){
  const {data,error,retry}=useAdminData<ResponseRow[]>("/api/admin/responses");const [query,setQuery]=useState("");const [submission,setSubmission]=useState("all");
  const questions=Array.from({length:30},(_,i)=>`Q${String(i+1).padStart(2,"0")}`);
  const filtered=useMemo(()=>data?.filter(row=>`${row.user_id} ${row.assessment_id}`.toLowerCase().includes(query.toLowerCase())&&(submission==="all"||(submission==="submitted"?Boolean(row.submitted_at):!row.submitted_at)))||[],[data,query,submission]);
  if(!data)return <LoadState error={error} retry={retry}/>; if(!data.length)return <NoRows label="jawaban"/>;
  return <><AdminPageNote>Setiap baris adalah satu assessment. Kolom Q01–Q30 disimpan berdampingan agar mudah diperiksa dan dianalisis.</AdminPageNote><div className="table-card raw-table"><div className="filter-bar"><input aria-label="Cari jawaban" placeholder="Cari respondent atau assessment…" value={query} onChange={event=>setQuery(event.target.value)}/><select aria-label="Filter pengiriman" value={submission} onChange={event=>setSubmission(event.target.value)}><option value="all">Semua jawaban</option><option value="submitted">Sudah dikirim</option><option value="draft">Masih berlangsung</option></select><span>{filtered.length} assessment</span></div>{filtered.length?<><div className="table-scroll raw-desktop"><table><thead><tr><th>Respondent ID</th><th>Assessment</th>{questions.map(q=><th key={q}>{q}</th>)}<th>Diperbarui</th></tr></thead><tbody>{filtered.map(row=><tr key={row.assessment_id}><td><Link href={`/admin/pengguna/${encodeURIComponent(row.user_id)}`}><strong>{row.user_id}</strong></Link></td><td>{row.assessment_id}</td>{questions.map(q=><td key={q}>{row[q]||"—"}</td>)}<td>{row.updated_at?new Date(row.updated_at).toLocaleString("id-ID"):"—"}</td></tr>)}</tbody></table></div><div className="raw-mobile-list">{filtered.map(row=><details key={row.assessment_id}><summary><strong>{row.user_id}</strong><span>{Object.keys(row).filter(key=>/^Q\d{2}$/.test(key)&&row[key]).length}/30 jawaban</span></summary><p>{row.assessment_id}</p><div>{questions.map(q=><span key={q}><b>{q}</b>{row[q]||"—"}</span>)}</div><Link href={`/admin/pengguna/${encodeURIComponent(row.user_id)}`}>Lihat detail responden →</Link></details>)}</div></>:<NoRows label="hasil yang cocok"/>}</div></>
}

type AdminResult={assessmentId:string;userId:string;calculatedAt:string;strategies:Array<{key:string;label:string;score:number;category:string}>};
export function AdminResults(){
  const {data,error,retry}=useAdminData<AdminResult[]>("/api/admin/results"); if(!data)return <LoadState error={error} retry={retry}/>; if(!data.length)return <NoRows label="hasil pengukuran"/>;
  const labels=data[0]?.strategies||[];
  return <><div className="demo-banner"><Info/><p><strong>Skor resmi per subskala.</strong><span>Masing-masing adalah jumlah tiga butir dengan rentang 3–21; tidak ada skor total.</span></p></div><div className="table-card raw-table"><div className="filter-bar"><span>{data.length} hasil</span></div><div className="table-scroll"><table><thead><tr><th>Respondent ID</th><th>Assessment</th>{labels.map(s=><th key={s.key}>{s.label}</th>)}<th>Dihitung</th></tr></thead><tbody>{data.map(result=><tr key={result.assessmentId}><td><Link href={`/admin/pengguna/${encodeURIComponent(result.userId)}`}><strong>{result.userId}</strong></Link></td><td>{result.assessmentId}</td>{result.strategies.map(strategy=><td key={strategy.key}>{strategy.score} · {strategy.category==="high"?"Tinggi":strategy.category==="low"?"Rendah":"Rata-rata"}</td>)}<td>{new Date(result.calculatedAt).toLocaleString("id-ID")}</td></tr>)}</tbody></table></div></div></>
}

type InstrumentRow={id:string;question_number:number;question_text_en:string;question_text_id:string;strategy:string;scale_min:number;scale_max:number;translation_status:string;is_active:boolean|string};
export function AdminInstrument(){
  const {data,error,retry}=useAdminData<InstrumentRow[]>("/api/admin/instrument"); if(!data)return <LoadState error={error} retry={retry}/>; if(!data.length)return <NoRows label="butir instrumen"/>;
  const active=data.filter(item=>item.is_active===true||String(item.is_active).toLowerCase()==="true").length;
  return <><AdminPageNote>Teks Inggris berasal dari PDF resmi Preece &amp; Gross (2026). Teks Indonesia adalah terjemahan proyek berstatus draft_translation dan bukan versi Indonesia yang tervalidasi.</AdminPageNote><div className="instrument-summary"><div><strong>{data.length}</strong><span>Item ERQ-30</span></div><div><strong>{active}</strong><span>Item aktif</span></div></div><div className="table-card instrument-table"><div className="filter-bar"><span>{active===30?"Instrumen bilingual siap digunakan":"Jalankan seedErq30Questions() di Apps Script"}</span></div><div className="table-scroll"><table><thead><tr><th>Nomor</th><th>Bahasa Indonesia</th><th>English original</th><th>Strategi</th><th>Terjemahan</th><th>Skala</th><th>Status</th></tr></thead><tbody>{data.map(question=>{const active=question.is_active===true||String(question.is_active).toLowerCase()==="true";return <tr key={question.id}><td><strong>Q{String(question.question_number).padStart(2,"0")}</strong></td><td>{question.question_text_id||"—"}</td><td lang="en">{question.question_text_en}</td><td>{question.strategy}</td><td>{question.translation_status}</td><td>{question.scale_min}–{question.scale_max}</td><td><span className="locked"><LockKeyhole/>{active?"Aktif":"Nonaktif"}</span></td></tr>})}</tbody></table></div></div></>
}

type AdminUserDetailData={user:{id:string;name:string;email:string;status:string;created_at:string};biodata:Record<string,string>|null;assessments:Array<{id:string;status:string;started_at:string;completed_at:string}>;results:AdminResult[]};
export function AdminUserDetail({userId}:{userId:string}){
  const {data,error,retry}=useAdminData<AdminUserDetailData>(`/api/admin/users/${encodeURIComponent(userId)}`);if(!data)return <LoadState error={error} retry={retry}/>;
  return <div className="admin-overview"><section className="table-card"><div className="filter-bar"><span>Identitas responden</span></div><div className="table-scroll"><table><tbody><tr><th>ID</th><td>{data.user.id}</td></tr><tr><th>Nama</th><td>{data.biodata?.nama||data.user.name}</td></tr><tr><th>Email</th><td>{data.user.email}</td></tr><tr><th>Status akun</th><td>{data.user.status}</td></tr><tr><th>Usia</th><td>{data.biodata?.usia||"—"}</td></tr><tr><th>Jenis kelamin</th><td>{data.biodata?.jenis_kelamin||"—"}</td></tr><tr><th>Pendidikan</th><td>{data.biodata?.pendidikan||"—"}</td></tr><tr><th>Pekerjaan</th><td>{data.biodata?.pekerjaan||"—"}</td></tr><tr><th>Domisili</th><td>{data.biodata?.domisili||"—"}</td></tr></tbody></table></div></section><section className="table-card raw-table"><div className="filter-bar"><span>{data.assessments.length} assessment</span></div>{data.assessments.length?<div className="table-scroll"><table><thead><tr><th>ID</th><th>Status</th><th>Mulai</th><th>Selesai</th></tr></thead><tbody>{data.assessments.map(item=><tr key={item.id}><td>{item.id}</td><td><StatusBadge status={statusLabel[item.status]||item.status}/></td><td>{item.started_at?new Date(item.started_at).toLocaleString("id-ID"):"—"}</td><td>{item.completed_at?new Date(item.completed_at).toLocaleString("id-ID"):"—"}</td></tr>)}</tbody></table></div>:<NoRows label="assessment"/>}</section><section className="table-card raw-table"><div className="filter-bar"><span>{data.results.length} hasil</span></div>{data.results.length?<div className="table-scroll"><table><thead><tr><th>Assessment</th><th>Subskala</th><th>Skor</th><th>Kategori</th></tr></thead><tbody>{data.results.flatMap(result=>result.strategies.map(strategy=><tr key={`${result.assessmentId}-${strategy.key}`}><td>{result.assessmentId}</td><td>{strategy.label}</td><td>{strategy.score} / 21</td><td>{strategy.category==="high"?"Tinggi":strategy.category==="low"?"Rendah":"Rata-rata"}</td></tr>))}</tbody></table></div>:<NoRows label="hasil"/>}</section></div>
}
